### ISSUE TITLE
Discuss

### ISSUE THREAD

**Issue by sultan99** [richiemccoll/react-ramda-examples#1]
I think the `App` should be call `Post`:
https://github.com/richiemccoll/react-ramda-examples/blob/4f3ceee76a510ebbd91a153138225dfe6e6bf888/src/index.js#L99

**Comment by richiemccoll** [comment]
Hi @sultan99 I disagree, App is the entry point for ReactDOM and is a generic container name in React applications. There is also already a Post component in this example.
